### ISSUE TITLE
[Bug]: Refresh Icon Jitter Issue in Git Source Control Toolbar

### ISSUE THREAD

**Issue by YiyangNa** [Vinzent03/obsidian-git#916]
### Describe the bug

**Description**:

When using the Git plugin in Obsidian Mobile (Android), the refresh icon (🔄) in the bottom toolbar exhibits noticeable jitter/shaking upon clicking.

**Steps to Reproduce**:

1. Open Obsidian Mobile on an Android device
2. Navigate to a vault with Git plugin enabled
3. Click the refresh icon in Git Source Control's bottom toolbar
4. Observe the icon jitter phenomenon

**Additional Information**:
- Issue occurs only on mobile (desktop version works normally)
- Screen recording: https://github.com/user-attachments/assets/14a09ceb-4fb9-469e-ae01-30a1574e24b5

### Relevant errors (if available) from notifications or console (`CTRL+SHIFT+I`)

```shell

```

### Steps to reproduce

1. Open Obsidian Mobile on an Android device
2. Navigate to a vault with Git plugin enabled
3. Click the refresh icon in Git Source Control's bottom toolbar
4. Observe the icon jitter phenomenon

### Expected Behavior

The position of the icon remains unchanged.

### Addition context

The icon jiggles from side to side. 

### Operating system

Android

### Installation Method

None

### Plugin version

2.33.0

**Comment by SHNakajima** [comment]
The same issue occurs with all functions where the reload icon spins.

The plugin version is 2.34.0.

**Comment by Vinzent03** [comment]
Which theme are you using? I have no issues using the default or minimal theme.

**Comment by MiSawa** [comment]
I have the exact same issue;
- phone: Pixel 8
- obsidian-git version: 2.35.0
- theme: [things](https://github.com/colineckert/obsidian-things) (dark mode)

**Comment by Vinzent03** [comment]
As it works perfectly fine with the default theme, I think this is more an issue with the things theme. Please consider opening an issue in their repo. So I'm closing this issue for now. I'm willing to reopen this if there is a good explanation why this should be fixed by the plugin instead.

**Comment by MiSawa** [comment]
Actually I noticed that it reproduces even with the default theme in my environment.
https://github.com/user-attachments/assets/afe88917-c8c4-4a58-af33-43a21ccdd2cf

**Comment by Vinzent03** [comment]
Which Obsidian version are you using? The row with these buttons is not at the bottom in my version.

**Comment by MiSawa** [comment]
I'm on obsidian 1.8.10 (197)
Just updated to 1.8.10 (234) and the issue persists.
https://github.com/user-attachments/assets/b3e06791-4357-43f8-bc3b-f8aeaff39d8f

Thanks for the awesome plugin, by the way—it’s the one I rely on the most!

**Comment by SHNakajima** [comment]
This issue should be resolved in the next release with the fix from PR #941.
